const PRODUCTS = [{"id":"bag","title":"Pulse Jet Bag Filters","tag":"Dust collection","desc":"Self-cleaning filtration for fine, dry dust. Online and offline configurations.","images":["assets/filter.jpg","assets/gallery-bag-1.jpg","assets/gallery-bag-2.jpg","assets/gallery-bag-3.jpg","assets/gallery-bag-4.jpg","assets/gallery-bag-5.jpg","assets/gallery-bag-6.jpg"]},{"id":"blower","title":"Centrifugal Blowers / ID Fans","tag":"Air movement","desc":"Pressure and volume blowers for process ventilation and dust collection.","images":["assets/blower.jpg","assets/gallery-blower-1.jpg","assets/gallery-blower-2.jpg","assets/gallery-blower-3.jpg","assets/gallery-blower-4.jpg"]},{"id":"scrubber","title":"Industrial Scrubbers","tag":"Pollution control","desc":"Scrubber equipment for industrial air handling and treatment requirements.","images":["assets/gallery-scrubber-1.jpg"]},{"id":"valve","title":"Butterfly Valves","tag":"Flow control","desc":"Flow isolation for industrial applications, water treatment and refineries.","images":["assets/gallery-valve-4.jpg"]},{"id":"carbon","title":"Activated Carbon Filters","tag":"Filtration","desc":"Discuss your filtration application and carbon filter equipment requirements.","images":["assets/gallery-carbon-1.jpg"]},{"id":"rotor","title":"Rotors & Shaft Assemblies","tag":"Components","desc":"Rotor and shaft assemblies from our supplied manufacturing photographs.","images":["assets/gallery-rotor-1.jpg","assets/gallery-rotor-2.jpg"]},{"id":"fume","title":"Portable Welding Fume Extractor","tag":"Workplace air","desc":"Portable extraction at the welding source.","images":[]},{"id":"conveying","title":"Pneumatic Conveying System","tag":"Material handling","desc":"Enclosed transfer of dry powders and granular materials using airflow.","images":[]},{"id":"vapour","title":"Vapour Recovery Unit","tag":"Emission control","desc":"Recovery of tank vapours for storage and chemical applications.","images":[]},{"id":"downdraft","title":"Downdraft Table","tag":"Workplace safety","desc":"Extraction for grinding, buffing and welding workstations.","images":[]}];
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
if(reduced)document.body.classList.add('no-motion');
const $=id=>document.getElementById(id);
const waURL=msg=>'https://wa.me/919312893079?text='+encodeURIComponent(msg);
const greeting='Hello Aircon Systems, I visited your website and would like to discuss my project.';
['waFloat','waFooter','waCta'].forEach(id=>{const el=$(id);if(el){el.href=waURL(greeting);el.target='_blank';el.rel='noopener';}});
function tick(){const now=new Date();const t=now.toLocaleTimeString('en-IN',{timeZone:'Asia/Kolkata',hour:'numeric',minute:'2-digit',hour12:true});const d=now.toLocaleDateString('en-IN',{timeZone:'Asia/Kolkata',weekday:'long',day:'numeric',month:'long',year:'numeric'});['tbClockT','heroTime','footTime'].forEach(id=>{if($(id))$(id).textContent=t+' IST';});['tbDate','heroDate'].forEach(id=>{if($(id))$(id).textContent=d;});if($('footClock2'))$('footClock2').textContent=t+' IST';if($('year'))$('year').textContent=now.getFullYear();}tick();setInterval(tick,60000);
const nav=$('nav'),overlay=$('navOverlay'),burger=$('burger');
function setNav(open){$("header")?.classList.toggle("menu-open",open);nav?.classList.toggle('open',open);overlay?.classList.toggle('show',open);burger?.setAttribute('aria-expanded',String(open));burger?.setAttribute('aria-label',open?'Close menu':'Open menu');}
burger?.addEventListener('click',()=>setNav(!nav.classList.contains('open')));overlay?.addEventListener('click',()=>setNav(false));nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>setNav(false)));
const topButton=$('toTop');addEventListener('scroll',()=>{$('header')?.classList.toggle('scrolled',scrollY>60);topButton?.classList.toggle('show',scrollY>500);},{passive:true});topButton?.addEventListener('click',()=>scrollTo({top:0,behavior:reduced?'auto':'smooth'}));
let heroIndex=0,heroTimer=null,heroPaused=reduced;const slides=[...document.querySelectorAll('.slide')];const heroImages=['assets/hero.jpg','assets/blower.jpg','assets/scrubber.jpg'];
slides.forEach((slide,i)=>{slide.style.backgroundImage=`linear-gradient(90deg,rgba(8,28,43,.94) 10%,rgba(8,28,43,.82) 45%,rgba(8,28,43,.32)),url("${heroImages[i]}")`;const b=document.createElement('button');b.setAttribute('aria-label','Show equipment photograph '+(i+1));b.addEventListener('click',()=>{go(i);restartHero();});$('heroDots')?.appendChild(b);});
function go(i){heroIndex=i;slides.forEach((s,k)=>s.classList.toggle('active',k===i));$('heroDots')?.querySelectorAll('button').forEach((b,k)=>{b.classList.toggle('active',k===i);b.setAttribute('aria-pressed',String(k===i));});}
function restartHero(){clearInterval(heroTimer);if(slides.length&&!heroPaused&&!document.hidden)heroTimer=setInterval(()=>go((heroIndex+1)%slides.length),6500);}
if(slides.length){go(0);restartHero();$('heroNext')?.addEventListener('click',()=>{go((heroIndex+1)%slides.length);restartHero();});$('heroPrev')?.addEventListener('click',()=>{go((heroIndex+slides.length-1)%slides.length);restartHero();});$('heroPause')?.addEventListener('click',()=>{heroPaused=!heroPaused;$('heroPause').textContent=heroPaused?'▷':'Ⅱ';$('heroPause').setAttribute('aria-label',heroPaused?'Play slideshow':'Pause slideshow');restartHero();});document.addEventListener('visibilitychange',restartHero);}
let lbList=[],lbIndex=0,lbTitle='',lbTrigger=null;const lb=$('lightbox');
function showLB(){if(!lbList.length)return;$('lbImg').src=lbList[lbIndex];$('lbImg').alt=lbTitle+' photograph '+(lbIndex+1);$('lbCaption').textContent=lbTitle+' · '+(lbIndex+1)+' / '+lbList.length;}
function openLB(images,title,index,trigger){lbList=images;lbIndex=index;lbTitle=title;lbTrigger=trigger;showLB();lb.classList.add('open');document.body.style.overflow='hidden';$('lbClose').focus();}
function closeLB(){lb?.classList.remove('open');document.body.style.overflow='';lbTrigger?.focus();}
$('lbClose')?.addEventListener('click',closeLB);$('lbNext')?.addEventListener('click',()=>{lbIndex=(lbIndex+1)%lbList.length;showLB();});$('lbPrev')?.addEventListener('click',()=>{lbIndex=(lbIndex-1+lbList.length)%lbList.length;showLB();});lb?.addEventListener('click',e=>{if(e.target===lb)closeLB();});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeLB();setNav(false);}if(!lb?.classList.contains('open'))return;if(e.key==='ArrowRight')$('lbNext').click();if(e.key==='ArrowLeft')$('lbPrev').click();if(e.key==='Tab'){const buttons=[...lb.querySelectorAll('button')];const first=buttons[0],last=buttons[buttons.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
const prodGrid=$('prodGrid');if(prodGrid&&!prodGrid.children.length){PRODUCTS.forEach(p=>{const card=document.createElement('article');card.className='card prod-card reveal';card.id='product-'+p.id;card.innerHTML=(p.images.length?`<div class="prod-thumb"><img src="${p.images[0]}" alt="${p.title}" loading="lazy"><span class="tag">${p.tag}</span></div>`:`<div class="text-product"><small>${p.tag}</small><span>${p.title}</span></div>`)+`<div class="card-body prod-body"><h3>${p.title}</h3><p>${p.desc}</p><div class="card-cta">${p.images.length?'<button class="prod-more" type="button">View Photos</button>':''}<a class="prod-enquiry" target="_blank" rel="noopener" href="${waURL('Hello Aircon Systems, I would like to enquire about '+p.title+'.')}">Enquire</a></div></div>`;card.querySelector('.prod-more')?.addEventListener('click',e=>openLB(p.images,p.title,0,e.currentTarget));prodGrid.appendChild(card);});}
const galGrid=$('galGrid'),filters=$('filters');if(galGrid&&filters){const photos=PRODUCTS.filter(p=>p.images.length);filters.innerHTML=[{id:'all',title:'All Photos'},...photos].map((p,i)=>`<button class="chip ${i===0?'active':''}" data-filter="${p.id}" aria-pressed="${i===0}">${p.title}</button>`).join('');photos.forEach(p=>p.images.forEach((src,i)=>{const b=document.createElement('button');b.className='gal-item reveal';b.dataset.category=p.id;b.setAttribute('aria-label','View '+p.title+' photograph '+(i+1));b.innerHTML=`<img src="${src}" alt="${p.title}" loading="lazy"><span class="cap">${p.title}</span>`;b.addEventListener('click',()=>openLB(p.images,p.title,i,b));galGrid.appendChild(b);}));filters.addEventListener('click',e=>{const button=e.target.closest('[data-filter]');if(!button)return;const f=button.dataset.filter;filters.querySelectorAll('button').forEach(b=>{const active=b===button;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});galGrid.querySelectorAll('.gal-item').forEach(g=>{g.classList.toggle('hide',f!=='all'&&g.dataset.category!==f);g.classList.add('in');});});}
const select=$('fProduct');if(select)PRODUCTS.forEach(p=>{const o=document.createElement('option');o.value=p.title;o.textContent=p.title;select.appendChild(o);});
$('quoteForm')?.addEventListener('submit',e=>{e.preventDefault();const message=`New Enquiry — Aircon Systems\nName: ${$('fName').value.trim()}\nPhone: ${$('fPhone').value.trim()}\nEmail: ${$('fEmail').value.trim()||'Not supplied'}\nCity: ${$('fCity').value.trim()||'Not supplied'}\nProduct: ${$('fProduct').value}\nRequirement: ${$('fMsg').value.trim()||'Please contact me to discuss'}`;window.open(waURL(message),'_blank','noopener');});
if($('footProducts'))$('footProducts').innerHTML=PRODUCTS.map(p=>`<li><a href="index.html#product-${p.id}">${p.title}</a></li>`).join('');
if('IntersectionObserver' in window&&!reduced){const reveal=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');reveal.unobserve(e.target);}}),{threshold:.06});document.querySelectorAll('.reveal').forEach(el=>reveal.observe(el));const counter=new IntersectionObserver(entries=>entries.forEach(e=>{if(!e.isIntersecting)return;const el=e.target,target=Number(el.dataset.count),start=performance.now();function frame(now){const progress=Math.min((now-start)/1100,1);el.textContent=Math.round(target*(1-Math.pow(1-progress,3)));if(progress<1)requestAnimationFrame(frame);}requestAnimationFrame(frame);counter.unobserve(el);}),{threshold:.5});document.querySelectorAll('[data-count]').forEach(el=>counter.observe(el));}else{document.querySelectorAll('.reveal').forEach(el=>el.classList.add('in'));document.querySelectorAll('[data-count]').forEach(el=>el.textContent=el.dataset.count);}

